### ISSUE TITLE
회원가입시 이미 존재하는 이름의 경우 에러 메세지가 이상함

### ISSUE THREAD

**Issue by kyuwon53** [growth-ring/taskgrow#180]
![Image](https://github.com/growth-ring/taskgrow/assets/86951640/868ee51e-1b4a-4d70-b63b-94f8ac4f7351)

회원가입을 시도하니 예외메세지가 undefiend로 나옴. 
서버쪽 로그 확인해보니, 이미 존재하는 회원 이름으로 회원가입을 시도함. 
이미 존재하는 회원입니다. 와 같은 메세지가 나와야함.

**Comment by KJeeu** [comment]
로컬이랑 배포된 메인이랑 속성명이 서로 달라서 생기는 오류입니다.

아까 테스트해보니 로컬에서  undefinde 예외메세지가 떠서 확인해보니 로컬에 이전에는 메인과 같이 error속성명으로 들어왔는데 어느순간 reason속성명으로 바뀌어있어서 reason속성명값을 가져오도록 바꿔놨는데 메인에는 여전히 error속성명이었군요..

왜 서로 다른 속성명일까요..?

<로컬>
<img width="267" alt="image" src="https://github.com/growth-ring/taskgrow/assets/116357790/4f1f530f-f324-45e8-a236-067e5512a577">

<메인>
<img width="213" alt="image" src="https://github.com/growth-ring/taskgrow/assets/116357790/9cfb6190-3387-44ed-b016-e4897eb6905e">

**Comment by kyuwon53** [comment]
아!!!!!!!!
이런..... 백에서 에러 통합을 하면서, 변경된것을 공유를 안했군요....
ㅠㅠ 백에서 배포하면 돌아올거 같네요 ㅠㅠ
확인 감사합니다.
