### ISSUE TITLE
할 일 텍스트의 최대 길이가 너무 짧음

### ISSUE THREAD

**Issue by kyuwon53** [growth-ring/taskgrow#280]
![Image](https://github.com/growth-ring/taskgrow/assets/14071105/ee2844c9-06ab-4a7e-bd3c-dfff2777be5d)

`HTTP/2 in Action 읽기` 가 다 안써짐 ㅠㅜ

**Comment by kyuwon53** [comment]
글자수 50으로 늘립시당 cc. @KJeeu

**Comment by KJeeu** [comment]
할 일 텍스트의 최대 길이 50으로 늘렸습니다.
