### ISSUE TITLE
선택된 할 일이 잘 표시되지 않음

### ISSUE THREAD

**Issue by kyuwon53** [growth-ring/taskgrow#281]
![Image](https://github.com/growth-ring/taskgrow/assets/14071105/8e0c12c8-2c7c-409c-b4d4-94e6d9d8c178)

색깔만으로 표시하는건 별로 안좋음. 색약이 있으신 분들은 잘 구별못할수도 있을 수 있기 때문. 그래서 색깔말고도 티가날 수 있는게 좋을듯

**Comment by kyuwon53** [comment]
선택된 할 일은 박스 바깥으로 띠를 두르던가 두께감을 표시해서 색깔만으로 구분되지 않고 모양과 색깔 모두로 구분 될 수 있도록 하는 것은 어떨까요? 
cc.

**Comment by KJeeu** [comment]
![Image](https://github.com/growth-ring/taskgrow/assets/116357790/ef8a3635-9ff5-44ca-9810-896117924406)

박스 바깥에 띠를 두르는 식으로 모양과 색깔 모두로 구분 될 수 있도록 개선하였습니다.
